format = """
[î‚¶](fg:#9A0638 bg:#111111)\
[ ïŠ–  ](bg:#9a0638 fg:#ffffff)\
[î‚°](bg:#151E71 fg:#9A0638)\
$directory\
[î‚°](fg:#151E71 bg:#001647)\
$git_branch\
[î‚°](fg:#001647 bg:#001647)\
$git_status\
[î‚°](fg:#001647 bg:#890743)\
$git_state\
$git_metrics\
[î‚°](fg:#890743 bg:#120F23)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[î‚°](fg:#120F23 bg:#890743)\
$docker_context\
[î‚°](fg:#890743 bg:#)\
$time\
$line_break\
$character
"""


# Disable the blank line at the start of the prompt
# add_newline = false
 
# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#9A0638"
style_root = "bg:#9A0638"
format = '[$user ]($style)'
 
[directory]
style = "bg:#151E71"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
 
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " ïœ˜ "
"Downloads" = " ï€™ "
"Music" = " ïŸŠ "
"Pictures" = " ï‡… "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "
 
[c]
symbol = "Â© "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[character]
#success_symbol = "[ï‘„ï›—ï”](purple)"
#error_symbol = "[ï‘„ï›—ï”](red)"
#vicmd_symbol = "[ï„„ï›—ï‘„](green)"

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'
 
[elixir]
symbol = "ğŸ’§ "
style = "bg:#7aa2f7"
format = '[[ $symbol ($version) ](bg:#7aa2f7)]($style)'
 
[elm]
symbol = "ğŸŒ³ "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
 
[git_branch]
symbol = "îœ¥"
style = "bg:#001647"
format = '[[ $symbol $branch](bg:#001647)]($style)'
 
[git_status]
style = "bg:#001647"
format = '[[($all_status$ahead_behind )](bg:#001647)]($style)'
 
[git_state]
style = "bg:#890743"
format = '([ $state( $progress_current/$progress_total )]($style)) '

[git_metrics]
added_style = "#1a1b26"
format = '([ +$added ](bg:#890743))([-$deleted ](bg:#890743))'
disabled = false

[golang]
symbol = "ğŸ¹ "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
 
[haskell]
symbol = "Î» "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
 
[java]
symbol = "ïƒ´ "
style = "bg:#120F23"
format = '[[ $symbol ($version) ](bg:#120F23)]($style)'
 
[julia]
symbol = "à®ƒ "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
 
[nodejs]
symbol = "îœ˜"
style = "bg:#120F23"
format = '[[ $symbol ($version) ](bg:#120F23)]($style)'
 
[nim]
symbol = "ğŸ‘‘ "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
 
[rust]
symbol = "ğŸ¦€"
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

# [battery]
# full_symbol = "ï‰€  "
# charging_symbol = "ïƒ§ "
# discharging_symbol = "ï‰€  "
# format = '[$symbol$percentage]($style) '
# disabled = false
#
# [[battery.display]]
# threshold = 30
# style = "bold red"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#0b143b"
format = '[[ ï‡š $time ](bg:#)]($style)'
